version: '2'
networks:
  default:
    external:
      name: infrastructure-net

services:
  nginx-proxy:
    image: nexus-docker.dvo-novibet.systems/bluebrown-web/novi-proxy:latest
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
